
import { GoogleGenAI, Type } from "@google/genai";
import { Quote, Language } from "../types";

let quotaExhausted = false;

/**
 * Generates only the text content of quotes.
 * Mixes real historical quotes and AI-generated ones.
 */
export const generateQuotes = async (count: number = 3, lang: Language = 'English', exclude: string[] = []): Promise<Quote[]> => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    console.warn("API Key missing, skipping AI generation");
    return [];
  }

  const ai = new GoogleGenAI({ apiKey });
  
  const excludeStr = exclude.length > 0 ? `Do NOT return any of these quotes: ${exclude.slice(-20).join(', ')}.` : '';

  try {
    const response = await ai.models.generateContent({
      model: "gemini-flash-latest",
      contents: `You are Aletheia, the oracle of truth. Find ${count} inspiring quotes in ${lang}. 
      CRITICAL REQUIREMENT:
      1. Provide at least 80% real historical quotes from famous philosophers, writers, or thinkers (e.g., Marcus Aurelius, Rumi, Seneca, Victor Hugo, Albert Camus, Simone de Beauvoir, Antoine de Saint-Exupéry).
      2. Provide exactly 20% original quotes generated by your artificial intelligence.
      3. For real quotes, use the actual author's name and set "isAI": false.
      4. For AI quotes, use "Aletheia" as the author and set "isAI": true.
      5. SAFETY: All content must be safe for all ages (G-rated). No mature themes, violence, or sensitive topics.
      
      ${excludeStr} 
      
      Return ONLY a JSON array:
      [{"text": "the quote", "author": "author name", "category": "Wisdom/Love/Success/Life", "imagePrompt": "visual style", "isAI": boolean}]`,
    });

    const text = response.text || "[]";
    let rawQuotes = [];
    try {
      const jsonMatch = text.match(/\[.*\]/s);
      rawQuotes = JSON.parse(jsonMatch ? jsonMatch[0] : text);
    } catch (e) {
      console.error("JSON Parse Error", e);
      return [];
    }

    return rawQuotes.map((q: any) => ({
      id: Math.random().toString(36).substr(2, 9),
      text: q.text,
      author: q.author,
      category: q.category,
      imageUrl: undefined, 
      imagePrompt: q.imagePrompt || q.text,
      isLiked: false,
      isAI: !!q.isAI
    }));
  } catch (error: any) {
    console.error("Generate Quotes Error", error);
    return [];
  }
};

/**
 * Generates an image for a specific prompt.
 */
export const generateQuoteImage = async (prompt: string): Promise<string> => {
  if (quotaExhausted) return `https://picsum.photos/seed/${Math.random()}/1080/1920`;

  const apiKey = process.env.API_KEY;
  if (!apiKey) return `https://picsum.photos/seed/${Math.random()}/1080/1920`;

  try {
    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: [{ text: `High-end minimalist aesthetic background, cinematic photography, depth of field, 9:16 aspect ratio, concept: ${prompt}. No text on image.` }] },
      config: { imageConfig: { aspectRatio: "9:16" } }
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    return `https://picsum.photos/seed/${Math.random()}/1080/1920`;
  } catch (error: any) {
    if (error?.status === 429) {
      quotaExhausted = true;
      setTimeout(() => { quotaExhausted = false; }, 60000);
    }
    return `https://picsum.photos/seed/${Math.random()}/1080/1920`;
  }
};
